apiVersion: v1
kind: Service
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: release-name
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: postgresql
    release: release-name
