apiVersion: v1
kind: Secret
metadata:
  name: sentry-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.18.0
    release: release-name
    heritage: Tiller
type: Opaque
data:
  postgres-password: '{{repl ConfigOption "embedded_postgres_password" | Base64Encode}}'
