apiVersion: v1
kind: Secret
metadata:
  name: sentry-redis
  labels:
    app: redis
    chart: redis-3.8.1
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:
  redis-password: "TmVDS3J6cWc4aw=="
