apiVersion: v1
kind: Service
metadata:
  name: sentry-redis-slave
  labels:
    app: redis
    chart: redis-3.8.1
    release: "release-name"
    heritage: "Tiller"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "release-name"
    role: slave
