apiVersion: v1
kind: Secret
metadata:
  name: sentry-sentry
  labels:
    app: sentry-sentry
    chart: "sentry-2.0.1"
    release: "release-name"
    heritage: "Tiller"
type: Opaque
data:

  sentry-secret: "NmhEcU9hZFh2SklsZE00MVo4SFZmSEVhOEJ6OElxQXFYTVVzdXBzYQ=="

  smtp-password: ""


  user-password: "OTdXZ2N6ejluYVYxTFY4Ng=="
