kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sentry-sentry
  labels:
    app: sentry-sentry
    chart: "sentry-2.0.1"
    release: "release-name"
    heritage: "Tiller"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "100Gi"
