apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: sentry-enterprise
spec:
  groups:
    - name: sentry
      title: Sentry
      description: Sentry Defaults
      items:
        - name: hostname
          title: Admin Username
          type: text
          default: 'sentry.mycompany.com'
        - name: admin_username
          title: Admin Username
          type: text
          default: 'admin'
        - name: admin_password
          title: Admin Password
          type: password
          default: 'password'
        - name: secret_key
          title: Secret Key
          type: password
          hidden: true
          value: "{{repl RandomString 40}}"
    - name: database
      title: Database
      description: Database Options
      items:
        - name: postgres_type
          type: select_one
          title: Postgres
          default: embedded_postgres
          items:
            - name: embedded_postgres
              title: Embedded Postgres
            - name: external_postgres_inline
              title: External Postgres Inline
            - name: external_postgres_secret
              title: External Postgres From Secret
        - name: embedded_postgres_password
          hidden: true
          type: password
          value: "{{repl RandomString 32}}"
        - name: external_postgres_host
          title: Postgres host
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          default: db.mycompany.internal
        - name: external_postgres_port
          title: Postgres Port
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: text
          default: '5432'
        - name: external_postgres_password
          title: Postgres Password
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
          type: password
        - name: external_postgres_secretname
          title: Postgres Secret Name
          help_text: Enter the name of a secret containing the key `PG_CONNSTRING`
          when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_secret"}}'
          type: text

