apiVersion: v1
kind: Secret
metadata:
  name: sentry
  labels:
    app: sentry
type: Opaque
data:
  sentry-secret: "NmhEcU9hZFh2SklsZE00MVo4SFZmSEVhOEJ6OElxQXFYTVVzdXBzYQ=="
  smtp-password: ""
  user-password: "OTdXZ2N6ejluYVYxTFY4Ng=="
