apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: gitlab
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: sentry
    chartVersion: 3.1.7

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    ingress:
      enabled: true
      hostname: repl{{ConfigOption "hostname" }}
    metrics:
      enabled: true
    postgresql:
      enabled: repl{{ if ConfigOptionEquals "postgres_type" "embedded_postgres"}}truerepl{{ else }}falserepl{{ end }}
      nameOverride: sentry-postgresql
      postgresqlDatabase: sentry
      postgresqlUsername: postgres
      postgresqlHost: repl{{ConfigOption "external_postgres_host"}}
      postgresqlPassword: repl{{ConfigOption "external_postgres_password"}}
      postgresqlPort: repl{{ConfigOption "external_postgres_port"}}



  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
