apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: sentry-enterprise
spec:
  collectors:
    - secret:
        name: myapp-postgres
        key: uri
        includeValue: false
    - logs:
        collectorName: sentry-all
        name: sentry/logs
        selector:
          - component=sentry
    - run:
        collectorName: ping-google
        image: flungo/netutils
        command: ["ping"]
        args: ["www.google.com"]
        timeout: 5s
    - http:
        collectorName: echo-ip
        get:
          url: https://api.replicated.com/market/v1/echo/ip
  analyzers:
    # Fails on preflight page even though registry has been added vendor.replicated.com.
    - imagePullSecret:
        checkName: Has Access to index.docker.io
        registryName: index.docker.io
        outcomes:
          - fail:
              message: Cannot pull from index.docker.io
          - pass:
              message: Found credentials to pull from index.docker.io
    # Fails on preflight page even though Ingress exists.
    - ingress:
        ingressName: sentry-ingress
        outcomes:
          - fail:
              message: Sentry ingress is not working.
          - pass:
              message: Sentry ingress is working.
    - deploymentStatus:
        name: sentry-worker
        outcomes:
          - fail:
              when: "< 1"
              message: The Sentry Worker deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The Sentry Worker deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the Sentry Worker deployment ready.
    # Is it statefulset or statefulsetStatus?
    # Does not even show up in preflights page.
    - statefulsetStatus:
        name: sentry-redis-master
        outcomes:
          - fail:
              when: "< 1"
              message: The API deployment does not have any ready replicas.
          - warn:
              when: "= 1"
              message: The API deployment has only a single ready replica.
          - pass:
              message: There are multiple replicas of the API deployment ready.
    - clusterVersion:
        outcomes:
          - fail:
              when: "< 1.13.0"
              message: Sentry requires at Kubernetes 1.13.0 or later, and recommends 1.15.0.
              uri: https://www.kubernetes.io
          - warn:
              when: "< 1.15.0"

